name: CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build React application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Use node
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: ./client
        run: npm install
      
      - name: Build application
        working-directory: ./client
        run: npm run build
      
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: application-build
          path: ./client/build

  deploy:
    needs: build
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'
      
      - name: Deploy stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: MyStackerino
          template: cloudformation.yml
          no-fail-on-empty-changeset: "1"
          
      - name: Get build
        uses: actions/download-artifact@v1
        with:
          name: application-build

      - name: Deploy to S3
        run: aws s3 sync application-build s3://taylalex.com --acl public-read



